/*
 *  Minecraft Application Backup Utility: A multi-platform backup utility for Minecraft running on java
 *  Copyright (C) 2013 Jahed Hossain
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 *  Contact Author: jahedev@gmail.com
 */

package mabu.panels;

import mabu.AboutDialog;
import mabu.Debug;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JDialog;

/**
 *
 * @author Jahed
 */
public class AboutPanel extends javax.swing.JPanel
{
    JDialog dialog;
    Debug debug;
    Desktop desktop;
    
    /**
     * Creates new form AboutPanel
     */
    public AboutPanel(AboutDialog d)
    {
        dialog = d;
        debug = new Debug();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        aboutText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        imageLabel = new javax.swing.JLabel();
        createdByText = new javax.swing.JLabel();
        creatorText = new javax.swing.JLabel();
        createdByText1 = new javax.swing.JLabel();
        sourceforgeLink = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        createdByText2 = new javax.swing.JLabel();
        sourceforgeLink1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(48, 48, 48));
        setForeground(new java.awt.Color(255, 255, 255));

        aboutText.setBackground(new java.awt.Color(48, 48, 48));
        aboutText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        aboutText.setForeground(new java.awt.Color(255, 255, 255));
        aboutText.setText("About");

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mabu/resources/banner.png"))); // NOI18N

        createdByText.setBackground(new java.awt.Color(48, 48, 48));
        createdByText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createdByText.setForeground(new java.awt.Color(255, 255, 255));
        createdByText.setText("Created by:");

        creatorText.setBackground(new java.awt.Color(48, 48, 48));
        creatorText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        creatorText.setForeground(new java.awt.Color(255, 255, 255));
        creatorText.setText("Copyright © Jahed Hossain 2013");

        createdByText1.setBackground(new java.awt.Color(48, 48, 48));
        createdByText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createdByText1.setForeground(new java.awt.Color(255, 255, 255));
        createdByText1.setText("Website:");

        sourceforgeLink.setBackground(new java.awt.Color(48, 48, 48));
        sourceforgeLink.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        sourceforgeLink.setForeground(new java.awt.Color(153, 153, 255));
        sourceforgeLink.setText("<html><span style=\"text-decoration: underline;\">Sourceforge Project</span></html>");
        sourceforgeLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sourceforgeLink.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                sourceforgeLinkMouseClicked(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        createdByText2.setBackground(new java.awt.Color(48, 48, 48));
        createdByText2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createdByText2.setForeground(new java.awt.Color(255, 255, 255));
        createdByText2.setText("License:");

        sourceforgeLink1.setBackground(new java.awt.Color(48, 48, 48));
        sourceforgeLink1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        sourceforgeLink1.setForeground(new java.awt.Color(153, 153, 255));
        sourceforgeLink1.setText("<html><span style=\"text-decoration: underline;\">GPL v3</span></html>");
        sourceforgeLink1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sourceforgeLink1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                sourceforgeLink1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createdByText1)
                        .addGap(25, 25, 25)
                        .addComponent(sourceforgeLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aboutText)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(createdByText)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(creatorText)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createdByText2)
                                .addGap(25, 25, 25)
                                .addComponent(sourceforgeLink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(imageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdByText)
                    .addComponent(creatorText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdByText1)
                    .addComponent(sourceforgeLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceforgeLink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createdByText2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        dialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sourceforgeLinkMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sourceforgeLinkMouseClicked
    {//GEN-HEADEREND:event_sourceforgeLinkMouseClicked
        if (Desktop.isDesktopSupported())
        {
            desktop = Desktop.getDesktop();
            try
            {
                desktop.browse(URI.create("http://sourceforge.net/p/minecraft-backup-and-restore"));
            } catch (Exception ex)
            {
                debug.printDebugInfo("Error: On opening a link: " + ex);
            }
        }
    }//GEN-LAST:event_sourceforgeLinkMouseClicked

    private void sourceforgeLink1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_sourceforgeLink1MouseClicked
    {//GEN-HEADEREND:event_sourceforgeLink1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceforgeLink1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutText;
    private javax.swing.JLabel createdByText;
    private javax.swing.JLabel createdByText1;
    private javax.swing.JLabel createdByText2;
    private javax.swing.JLabel creatorText;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel sourceforgeLink;
    private javax.swing.JLabel sourceforgeLink1;
    // End of variables declaration//GEN-END:variables
}
